# It was generated by `nixos-generate-config`.
{ config, lib, pkgs, modulesPath, ... }:


{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ ];
  boot.extraModulePackages = [ ];

  hardware.cpu.intel.updateMicrocode = config.hardware.enableRedistributableFirmware;

  hardware.nvidia = {
    open = true;
    dynamicBoost.enable = true;
    powerManagement.enable = true;
    prime = {
      offload = {
        enable = true;
        enableOffloadCmd = true;
      };
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };
  };

  services.xserver = {
    videoDrivers = [ "nvidia" ];
    dpi = 192;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4ae84dd0-cb8b-4476-b853-7b7b865e17d9";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B52E-2C0E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
}
