# It was generated by `nixos-generate-config`.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    # sudo nix-channel --add https://github.com/NixOS/nixos-hardware/archive/master.tar.gz nixos-hardware
    <nixos-hardware/common/gpu/intel>
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "acpi_osi=linux" ];
  boot.extraModulePackages = [ ];

  hardware.cpu.intel.updateMicrocode = config.hardware.enableRedistributableFirmware;
  hardware.intelgpu.enableHybridCodec = true;

  services.xserver.dpi = 192;

  # Enable the temperature management daemon for fanless laptop.
  services.thermald.enable = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/57e72abb-a0d2-4f22-84ce-5d67eb9c48eb";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D066-BF7A";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/e24b12af-4476-4fde-99a8-a1197f84cb97"; }
  ];
}
