# It was generated by `nixos-generate-config`.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # This laptop has no nvidia card, just disable all related drivers.
  hardware.nvidiaOptimus.disable = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/24a14cea-2978-4ad0-9156-79e8e074ce0b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/15D9-7239";
    fsType = "vfat";
  };

  fileSystems."/media/ubuntu" = {
    device = "/dev/disk/by-uuid/8eb1aec6-4a38-47ae-aeb2-8e73cd4c9078";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/2638ce59-c2b9-4178-a2da-c3d02d3b3d78"; }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
